### ISSUE TITLE
`cassandra_path` variable is not defined nor documented

### ISSUE THREAD

**Issue by nkakouros** [locp/ansible-role-cassandra#116]
**Describe the bug**
Some of the experimental join_cluster.yml tasks contain tasks that reference the variable `cassandra_path`. This variable is not defined nor documented anywhere.

I also noticed [this line](https://github.com/locp/ansible-role-cassandra/blob/ecfaaa4179c66a939b57a681a00223361c2ec991/tasks/join_cluster.yml#L52) which given the structure of the `cassandra_directories` variable does not seem right.

Edit:
I also noticed that if you set cassandra_path to e.g. `/var/lib/cassandra` and it gets deleted, then cassandra does not have permission to recreate the directory.

**Comment by dallinb** [comment]
You're right, `cassandra_path` is not documented and should be.  Thinking back (and it was some time ago), I think the idea was that you would either have `cassandra_path` _or_ `cassandra_directories` defined.  I'll clarify that in the documentation and see what can be done about the recreation.

More alarmingly, you're also right that the paths in the removal are not correct (as seen in this test log https://github.com/locp/ansible-role-cassandra/runs/1875054828?check_suite_focus=true#step:7:84) will work on this over the weekend to get patched.

**Comment by nkakouros** [comment]
Actually, what got me into the `join-cluster.yml` is the fact that at least on Ubuntu, if you install cassandra, it immediately starts. Then, after installation, the role will configure cassandra as expected, including changing the cluster name, the racks, datacenters, etc. Then, cassandra may be restarted by the role. The problem here is that although the systemd service restarts fine, cassandra is actually broken because the config has e.g. a new cluster name (or the node belongs to e.g. DC1) but the node data contain the old cluster name (or datacenter).

**Comment by dallinb** [comment]
Yeah, that has been a problem it was raised as [CASSANDRA-2356](https://issues.apache.org/jira/browse/CASSANDRA-2356) back in 2011, but hasn't hit me as only testing on Docker containers.

**Comment by nkakouros** [comment]
I could spend some time working on this and potentially changing a bit the structure of tasks/main.yml (splitting it into a couple separate files, such as `install.yml`, `configure.yml`, `service.yml`). Would you be open to this?

**Comment by dallinb** [comment]
Always open to PRs (see https://github.com/locp/ansible-role-cassandra/blob/develop/CONTRIBUTING.md), but let me fix the issue with the incorrect directory names first and get a patch out (should be done by tomorrow) and then go ahead.

**Comment by dallinb** [comment]
I've just released 1.6.7 which fixes the more dangerous issue that you pointed out.  As you can see in this test transcript https://github.com/locp/ansible-role-cassandra/runs/1892782182?check_suite_focus=true#step:7:85 the files being removed look a lot more sane!  Please feel free to submit a PR when you get the time for the remaining issues.

**Comment by dallinb** [comment]
I'm going to use your new assertions to deprecate `cassandra_path` in favour of `cassandra_directories` see https://github.com/locp/ansible-role-cassandra/pull/120
