### ISSUE TITLE
Error installing 0.2.2 of the module from Galaxy.

### ISSUE THREAD

**Issue by dallinb** [locp/ansible-role-cassandra#13]
```
Using /private/var/tmp/ansible.cfg as config file
- downloading role 'cassandra', owned by locp
- downloading role from https://github.com/locp/ansible-role-cassandra/archive/0.2.2.tar.gz
- extracting locp.cassandra to /private/var/tmp/roles/locp.cassandra
ERROR! Unexpected Exception, this is probably a bug: [Errno 21] Is a directory: u'/private/var/tmp/roles/locp.cassandra'
```

Really not sure what is causing this as https://github.com/locp/ansible-role-cassandra/compare/0.2.1...0.2.2 does not exactly having anything jumping out at me as breaking this from 0.2.1 into 0.2.2.

**Comment by dallinb** [comment]
Other than `~rake_tasks` really can't see what fixed this (see https://github.com/locp/ansible-role-cassandra/compare/0.2.2...0.2.3), but installation works fine now.

**Comment by davividal** [comment]
I just faced a similar issue (with another role).
Since this is the only result from a google search, I'll post it here: it looks like ansible (galaxy?) will give this error if you have a file with a tilde (`~`) anywhere in its name.

**Comment by dallinb** [comment]
@davividal thanks for the update.  Admittedly I should have been checking what I was adding to my commit before that file ended up in the repository (subsequently added to the Git ignore file).  The further clarification is useful to know though.
